apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                  - pl-db
      containers:
      - name: postgres
        image: library/postgres:15-alpine
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "50Mi"
            cpu: "250m"
          limits:
            memory: "100Mi"
            cpu: "1000m"
        env:
        - name: POSTGRES_USER
          value: "saleor"
        - name: POSTGRES_PASSWORD
          value: "saleor"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data/
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 5432
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cache
spec:
  serviceName: cache
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:8.1-alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "20Mi"
            cpu: "100m"
          limits:
            memory: "80Mi"
            cpu: "500m"
        volumeMounts:
        - name: cache-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: cache-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  ports:
  - port: 6379
  selector:
    app: cache