apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saleor-media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: saleor-config
data:
  DASHBOARD_URL: "http://localhost:9000/"
  ALLOWED_HOSTS: "localhost,127.0.0.1,api"
  DATABASE_URL: "postgresql://saleor:saleor@db:5432/saleor"
  CELERY_BROKER_URL: "redis://cache:6379/0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saleor-media-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi