gcloud beta container \
    --project \
"project-098a5687-2092-4e52-995" clusters create "cl-m300" \
    --zone \
"us-central1-a" \
    --no-enable-basic-auth \
    --cluster-version \
"1.35.3-gke.1389000" \
    --release-channel \
"regular" \
    --machine-type \
"e2-micro" \
    --image-type \
"COS_CONTAINERD" \
    --disk-type \
"pd-standard" \
    --disk-size \
"20" \
    --metadata \
disable-legacy-endpoints=true \
    --spot \
    --num-nodes \
"1" \
    --logging=SYSTEM,WORKLOAD \
    --monitoring=SYSTEM,STORAGE,POD,DEPLOYMENT,STATEFULSET,DAEMONSET,HPA,JOBSET,CADVISOR,KUBELET,DCGM \
    --enable-ip-alias \
    --network \
"projects/project-098a5687-2092-4e52-995/global/networks/default" \
    --subnetwork \
"projects/project-098a5687-2092-4e52-995/regions/us-central1/subnetworks/default" \
    --cluster-ipv4-cidr \
"/17" \
    --no-enable-intra-node-visibility \
    --default-max-pods-per-node \
"110" \
    --enable-ip-access \
    --security-posture=standard \
    --workload-vulnerability-scanning=disabled \
    --no-enable-google-cloud-access \
    --addons \
HorizontalPodAutoscaling,HttpLoadBalancing,NodeLocalDNS,GcePersistentDiskCsiDriver \
    --enable-autoupgrade \
    --enable-autorepair \
    --max-surge-upgrade \
1 \
    --max-unavailable-upgrade \
0 \
    --binauthz-evaluation-mode=DISABLED \
    --enable-managed-prometheus \
    --enable-shielded-nodes \
    --shielded-integrity-monitoring \
    --no-shielded-secure-boot \
    --node-locations \
"us-central1-a" \
&& \
gcloud beta container \
    --project \
"project-098a5687-2092-4e52-995" node-pools create "pl-db" \
    --cluster \
"cl-m300" \
    --zone \
"us-central1-a" \
    --node-version \
"1.35.3-gke.1389000" \
    --machine-type \
"e2-micro" \
    --image-type \
"COS_CONTAINERD" \
    --disk-type \
"pd-standard" \
    --disk-size \
"100" \
    --metadata \
disable-legacy-endpoints=true \
    --num-nodes \
"3" \
    --enable-autoupgrade \
    --enable-autorepair \
    --max-surge-upgrade \
1 \
    --max-unavailable-upgrade \
0 \
    --shielded-integrity-monitoring \
    --no-shielded-secure-boot \
    --node-locations \
"us-central1-a" \
&& \
gcloud beta container \
    --project \
"project-098a5687-2092-4e52-995" node-pools create "pl-worker" \
    --cluster \
"cl-m300" \
    --spot \
    --zone \
"us-central1-a" \
    --node-version \
"1.35.3-gke.1389000" \
    --machine-type \
"e2-micro" \
    --image-type \
"COS_CONTAINERD" \
    --disk-type \
"pd-standard" \
    --disk-size \
"20" \
    --metadata \
disable-legacy-endpoints=true \
    --num-nodes \
"3" \
    --enable-autoupgrade \
    --enable-autorepair \
    --max-surge-upgrade \
1 \
    --max-unavailable-upgrade \
0 \
    --shielded-integrity-monitoring \
    --no-shielded-secure-boot \
    --node-locations \
"us-central1-a" \
&& \
gcloud beta container node-pools delete default-pool \
    --cluster "cl-m300" \
    --zone "us-central1-a" \
    --quiet
