image:
  pullPolicy: IfNotPresent
  repository: registry.rocket.chat/rocketchat/rocket.chat
  tag: 8.6.0-rc.2

mongodb:
  enabled: false

externalMongodbUrl: "<enter-external-mongodb-uri>"

microservices:
  enabled: true
replicaCount: 1

host: chat.kulici.ch

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: production-cert-issuer
  tls:
    - secretName: rckube
      hosts:
        - chat.kulici.ch
nats:
  cluster:
    name: rocketchat-nats-cluster