apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - pl-worker
      containers:
      - name: jaeger
        image: jaegertracing/jaeger
        ports:
        - containerPort: 16686
        - containerPort: 4317
        - containerPort: 4318
        volumeMounts:
        - name: tmpfs-volume
          mountPath: /tmp
        resources:
          requests:
            memory: "20Mi"
            cpu: "250m"
          limits:
            memory: "80Mi"
            cpu: "1000m"
      volumes:
      - name: tmpfs-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
  selector:
    app: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
      - name: mailpit
        image: axllent/mailpit
        ports:
        - containerPort: 1025
        - containerPort: 8025
        resources:
          requests:
            memory: "10Mi"
            cpu: "250m"
          limits:
            memory: "50Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: mailpit
spec:
  ports:
  - name: smtp
    port: 1025
    targetPort: 1025
  - name: webui
    port: 8025
    targetPort: 8025
  selector:
    app: mailpit